"""
Pre-build script: generate src/version_gen.h from git describe.

Output defines:
  FW_GIT_SHA       - short commit hash (7 chars)
  FW_GIT_DIRTY     - 1 if working tree has uncommitted changes, 0 otherwise
  FW_VERSION_MAJOR - parsed from semver tag (e.g. v1.2.3), else 0
  FW_VERSION_MINOR
  FW_VERSION_PATCH
"""
import subprocess
import re
import os

Import("env")  # noqa: F821 — injected by PlatformIO

OUT = os.path.join(env["PROJECT_SRC_DIR"], "version_gen.h")


def git(*args):
    try:
        return subprocess.check_output(["git"] + list(args),
                                       stderr=subprocess.DEVNULL).decode().strip()
    except subprocess.CalledProcessError:
        return ""


sha = git("rev-parse", "--short", "HEAD") or "unknown"
dirty = 1 if git("status", "--porcelain") else 0

# git describe --tags --long --dirty yields e.g. "v1.2.3-4-gabcdef0-dirty"
desc = git("describe", "--tags", "--long", "--dirty")
major = minor = patch = 0
if desc:
    m = re.match(r"v?(\d+)\.(\d+)\.(\d+)", desc)
    if m:
        major, minor, patch = int(m.group(1)), int(m.group(2)), int(m.group(3))

header = f"""\
/* Auto-generated by tools/gen_version.py — do not edit */
#pragma once
#define FW_GIT_SHA      "{sha}"
#define FW_GIT_DIRTY    {dirty}
#define FW_VERSION_MAJOR {major}
#define FW_VERSION_MINOR {minor}
#define FW_VERSION_PATCH {patch}
"""

with open(OUT, "w") as f:
    f.write(header)

print(f"gen_version.py: {sha}{'*' if dirty else ''} -> {major}.{minor}.{patch}")
